[mongodb] Add runtime dependencies of jnr for connecting to unix domain sockets
Presently when trying to connect to a Mongodb instace exposed as a unix domain
socket (e.g mongodb://run/mongodb/mongodb-<pid>.sock) following exception is reported:

Exception in thread "Thread-3" java.lang.NoClassDefFoundError:
jnr/unixsocket/UnixSocketAddress at
	com.mongodb.internal.connection.ServerAddressHelper.createServerAddress(ServerAddressHelper.java:31)
<snip/>
Caused by: java.lang.ClassNotFoundException: jnr.unixsocket.UnixSocketAddress
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
<snip/>

This is caused by missing runtime dependencies of
jnr-unixsocket (https://github.com/jnr/jnr-unixsocket) ,
jnr-ffi (https://github.com/jnr/jnr-ffi) and
jnr-constants (https://github.com/jnr/jnr-constants). These dependencies lets
the mongodb plugin connect to an db-instance via unix domain socket. Hence this
change adds these dependencies to mongodb plugin's pom.xml as runtime scoped
dependencies.